package ru.onalex.odashop.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "gruptov")
@Data
public class GrupTov {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    @Column(name = "code")
    private int id;

    //    purl varchar(250),
    @Column(name = "purl")
    private String purl;
    //    flpurl integer DEFAULT NULL,
    @Column(name = "flpurl")
    private int flpurl;
    //    code1 varchar(250),
    @Column(name = "code1")
    private String code1s; //id в 1С
    //    nomer integer DEFAULT NULL,
    @Column(name = "nomer")
    private int nomer;

    @Column(name = "vid")
    private int vid;
    //    cena numeric(10,2) DEFAULT NULL,
    @Column(name = "cena", columnDefinition = "numeric(10,2)")
    private double cena; //
    //    skidka numeric(10,2) DEFAULT NULL,
    @Column(name = "skidka", columnDefinition = "numeric(10,2)")
    private double skidka; //

    @Column(name="zakaz")
    private int zakaz;

    @Column(name="ost")
    @NotNull
    private int ost;
    //    blok integer DEFAULT NULL,
    @Column(name = "blok")
    private int blok;

    @Column(name = "rod", columnDefinition = "varchar(250)")
    private String rod;
    //    name varchar(250),
    @Column(name = "name")
    private String grupName;
    //    pic varchar(250),
    @Column(name = "pic")
    private String picPreview;

    @Column(name = "menu1")
    private int menu1;

    @Column(name = "menu2")
    private int menu2;

    @Column(name = "flmenu", columnDefinition = "varchar(250)")
    private String flmenu;
    //    top varchar(250),
    @Column(name = "top", columnDefinition = "varchar(250)")
    private String top;
    //    maingrup varchar(250),
    @Column(name = "maingrup", columnDefinition = "varchar(250)")
    private String maingrup;

    @Column(name = "razmerpic", columnDefinition = "varchar(250)")
    private String razmerpic;

    //    comment text,
    @Column(name = "comment", columnDefinition = "text")
    private String comment;

    @Column(name = "keywords", columnDefinition = "varchar(250)")
    private String keywords;

    @Column(name = "description", columnDefinition = "text")
    private String description;

    //    dop varchar(250),
    @Column(name = "dop", columnDefinition = "varchar(250)")
    private String dop;

    @OneToMany(mappedBy = "grupTov", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Tovar> tovarGrupSet = new HashSet<>();
}
