package ru.onalex.odashop.entities;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.NaturalId;

@Entity
@Table(name = "tovar")
@Data
public class Tovar {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    @Column(name = "code")
    private int id;

    //    purl varchar(250),
    @Column(name = "purl")
    private String purl;
    //    flpurl integer DEFAULT NULL,
    @Column(name = "flpurl")
    private int flpurl;
    //    code1 varchar(250),
    @Column(name = "code1")
    @NaturalId
    private String code1s; //id в 1С
    //    nomer integer DEFAULT NULL,
    @Column(name = "nomer")
    private int nomer;
    //    gruptov integer DEFAULT NULL,
    @Column(name = "gruptov")
    private int grupTov;
    //    name varchar(250),
    @Column(name = "name")
    private String tovName;
    //    pic varchar(250),
    @Column(name = "pic")
    private String picPreview;
    //    bpic varchar(250),
    @Column(name = "bpic")
    private String picBig;
    //    ostatok integer DEFAULT NULL,
    @Column(name = "ostatok")
    private int ostatok;
    //    cena numeric(10,2) DEFAULT NULL,
    @Column(name = "cena", columnDefinition = "numeric(10,2)")
    private double cena; //
    //    cena1 numeric(10,2) DEFAULT NULL,
    @Column(name = "cena1", columnDefinition = "numeric(10,2)")
    private double cena1; //
    //    ves numeric(10,3) DEFAULT NULL,
    @Column(name = "ves", columnDefinition = "numeric(10,3)")
    private double ves; //
    //    blok integer DEFAULT NULL,
    @Column(name = "blok")
    private int blok;
    //    data varchar(10),
    @Column(name = "data", columnDefinition = "varchar(10)")
    private String data;
    //    data_red varchar(250),
    @Column(name = "data_red", columnDefinition = "varchar(250)")
    private String dataRed;
    //    top varchar(250),
    @Column(name = "top", columnDefinition = "varchar(250)")
    private String top;
    //    dop_parametru varchar(250),
    @Column(name = "dop_parametru", columnDefinition = "varchar(250)")
    private String dopParametru;
    //    link varchar(250),
    @Column(name = "link", columnDefinition = "varchar(250)")
    private String link;
    //    prosmotru integer DEFAULT NULL,
    @Column(name = "prosmotru")
    private int prosmotru;
    //    comment text,
    @Column(name = "comment", columnDefinition = "text")
    private String comment;
    //    comment1 text,
    @Column(name = "comment1", columnDefinition = "text")
    private String comment1;
    //    dop varchar(250),
    @Column(name = "dop", columnDefinition = "varchar(250)")
    private String dop;
}
